name: Build and Deploy
on: push
env:
  CNAME: "barcode-scanner.mahdi.pro"
jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm ci
      - name: Build site
        run: npm run build
      - name: Add CNAME
        run: echo $CNAME > build/CNAME
      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Deploy site to Github Pages
        run: npx gh-pages -d build
